version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: unicorn-commander:${TAG:-latest}
    container_name: unicorn-commander
    restart: unless-stopped
    ports:
      - "${PORT:-8081}:${PORT:-8081}"
    environment:
      - NGINX_PORT=${PORT:-8081}
    networks:
      - unicorn-net

networks:
  unicorn-net:
    driver: bridge
