version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: unicorn-commander:${TAG:-latest}
    container_name: unicorn-commander
    restart: unless-stopped
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network
    volumes:
      - nginx-cache:/var/cache/nginx
      - nginx-run:/var/run/nginx
      - nginx-conf:/etc/nginx/conf.d
    environment:
      - NODE_ENV=production

networks:
  app-network:
    driver: bridge

volumes:
  nginx-cache:
  nginx-run:
  nginx-conf:
