version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: unicorn-commander:${TAG:-latest}
    container_name: unicorn-commander
    restart: unless-stopped
    ports:
      - "${PORT:-7000}:${PORT:-7000}"
    environment:
      - NGINX_PORT=${PORT:-7000}
    networks:
      - unicorn-net

networks:
  unicorn-net:
    driver: bridge
