version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT:-8080}
    image: unicorn-commander:${TAG:-latest}
    container_name: unicorn-commander
    restart: unless-stopped
    network_mode: host
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:${PORT:-8080}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - nginx-cache:/var/cache/nginx
      - nginx-run:/var/run/nginx
      - nginx-conf:/etc/nginx/conf.d
    environment:
      - PORT=${PORT:-8080}

volumes:
  nginx-cache:
  nginx-run:
  nginx-conf:
